# This file is used for development overrides
# It extends the main docker-compose.yml file

services:
  # Server API - Development overrides
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
      - /app/packages/shared-types/node_modules
      - /app/packages/shared-utils/node_modules
    command: npm run start:dev --workspace=apps/server

  # Worker Service - Development overrides
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3003
      MONGODB_URI: mongodb://admin:password@mongodb:27017/testdb?authSource=admin
      REDIS_URL: redis://redis:6379
      OVERDUE_TASK_CHECK_INTERVAL: "*/1 * * * *"
      ENABLE_OVERDUE_TASK_SCHEDULER: "true"
      LOG_LEVEL: debug
      ENABLE_CONSOLE_LOGGING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/worker/node_modules
      - /app/packages/shared-types/node_modules
      - /app/packages/shared-utils/node_modules
    command: npm run start:dev --workspace=apps/worker

  # Client Application - Development overrides
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/client/node_modules
      - /app/packages/shared-types/node_modules
      - /app/packages/shared-utils/node_modules
      - /app/apps/client/.next
    command: npm run dev --workspace=apps/client
