import { Task, TaskStatus, TaskPriority } from './task.model';
import { ORGANIZATIONS } from '../utils/organizations';

export const taskSeedData: Partial<Task>[] = [
  // Organization A Tasks (~30 tasks)
  // High Priority Tasks
  {
    title: 'Critical System Update',
    description: 'Update production system to latest version',
    priority: TaskPriority.URGENT,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com', // Will be replaced with actual user ID
    assignedTo: 'user2@orga.com',
    tags: ['deployment', 'security'],
    isOverdue: false,
  },
  {
    title: 'Security Audit',
    description: 'Conduct comprehensive security audit',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['security', 'testing'],
    isOverdue: false,
  },
  {
    title: 'Database Migration',
    description: 'Migrate database to new infrastructure',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['database', 'migration'],
    isOverdue: false,
  },
  {
    title: 'API Documentation',
    description: 'Complete API documentation for v2.0',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['documentation', 'api'],
    isOverdue: false,
  },
  {
    title: 'Performance Optimization',
    description: 'Optimize application performance',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['performance', 'optimization'],
    isOverdue: false,
  },

  // Medium Priority Tasks
  {
    title: 'User Interface Redesign',
    description: 'Redesign main dashboard interface',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user2@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['ui/ux', 'frontend'],
    isOverdue: false,
  },
  {
    title: 'Feature Implementation',
    description: 'Implement new reporting feature',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['feature', 'backend'],
    isOverdue: false,
  },
  {
    title: 'Code Review',
    description: 'Review pull requests for Q4 release',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['code-review', 'quality'],
    isOverdue: false,
  },
  {
    title: 'Testing Suite Update',
    description: 'Update automated testing suite',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['testing', 'automation'],
    isOverdue: false,
  },
  {
    title: 'Documentation Update',
    description: 'Update user documentation',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user2@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['documentation', 'user-guide'],
    isOverdue: false,
  },
  {
    title: 'Bug Fixes',
    description: 'Fix reported bugs in production',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['bug-fix', 'production'],
    isOverdue: false,
  },
  {
    title: 'Integration Testing',
    description: 'Test third-party integrations',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['testing', 'integration'],
    isOverdue: false,
  },
  {
    title: 'Monitoring Setup',
    description: 'Setup application monitoring',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['monitoring', 'devops'],
    isOverdue: false,
  },
  {
    title: 'Backup Strategy',
    description: 'Implement automated backup strategy',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['backup', 'devops'],
    isOverdue: false,
  },
  {
    title: 'User Training',
    description: 'Prepare user training materials',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['training', 'documentation'],
    isOverdue: false,
  },

  // Low Priority Tasks
  {
    title: 'Code Refactoring',
    description: 'Refactor legacy code modules',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user2@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['refactor', 'code-quality'],
    isOverdue: false,
  },
  {
    title: 'Log Analysis',
    description: 'Analyze application logs for patterns',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['analysis', 'logs'],
    isOverdue: false,
  },
  {
    title: 'Dependency Update',
    description: 'Update project dependencies',
    priority: TaskPriority.LOW,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['dependencies', 'maintenance'],
    isOverdue: false,
  },
  {
    title: 'Style Guide Update',
    description: 'Update coding style guide',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['style-guide', 'documentation'],
    isOverdue: false,
  },
  {
    title: 'Meeting Notes',
    description: 'Document team meeting notes',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user2@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['meeting', 'documentation'],
    isOverdue: false,
  },
  {
    title: 'Research Task',
    description: 'Research new technology options',
    priority: TaskPriority.LOW,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['research', 'technology'],
    isOverdue: false,
  },
  {
    title: 'Cleanup Task',
    description: 'Clean up old files and folders',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['cleanup', 'maintenance'],
    isOverdue: false,
  },
  {
    title: 'Email Templates',
    description: 'Create email notification templates',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['email', 'templates'],
    isOverdue: false,
  },
  {
    title: 'Analytics Setup',
    description: 'Setup user analytics tracking',
    priority: TaskPriority.LOW,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user2@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['analytics', 'tracking'],
    isOverdue: false,
  },
  {
    title: 'Accessibility Audit',
    description: 'Audit application accessibility',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['accessibility', 'audit'],
    isOverdue: false,
  },

  // Completed Tasks
  {
    title: 'Initial Setup',
    description: 'Complete project initial setup',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.COMPLETED,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'admin@orga.com',
    tags: ['setup', 'initialization'],
    isOverdue: false,
    completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
  },
  {
    title: 'Authentication System',
    description: 'Implement user authentication',
    priority: TaskPriority.HIGH,
    status: TaskStatus.COMPLETED,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'admin@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['authentication', 'security'],
    isOverdue: false,
    completedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
  },
  {
    title: 'Database Schema',
    description: 'Design and implement database schema',
    priority: TaskPriority.HIGH,
    status: TaskStatus.COMPLETED,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'manager@orga.com',
    assignedTo: 'user2@orga.com',
    tags: ['database', 'schema'],
    isOverdue: false,
    completedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
  },
  {
    title: 'Basic UI',
    description: 'Create basic user interface',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.COMPLETED,
    organizationId: ORGANIZATIONS.ORG_A.id,
    createdBy: 'user1@orga.com',
    assignedTo: 'user1@orga.com',
    tags: ['ui', 'frontend'],
    isOverdue: false,
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },

  // Organization B Tasks (~15 tasks)
  // High Priority Tasks
  {
    title: 'Client Onboarding',
    description: 'Onboard new client to platform',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['client', 'onboarding'],
    isOverdue: false,
  },
  {
    title: 'Data Migration',
    description: 'Migrate client data to new system',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['migration', 'data'],
    isOverdue: false,
  },
  {
    title: 'API Integration',
    description: 'Integrate with client API',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['api', 'integration'],
    isOverdue: false,
  },

  // Medium Priority Tasks
  {
    title: 'Report Generation',
    description: 'Generate monthly reports',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['reports', 'generation'],
    isOverdue: false,
  },
  {
    title: 'User Feedback',
    description: 'Collect and analyze user feedback',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['feedback', 'analysis'],
    isOverdue: false,
  },
  {
    title: 'Feature Testing',
    description: 'Test new features with users',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['testing', 'features'],
    isOverdue: false,
  },
  {
    title: 'Content Update',
    description: 'Update website content',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['content', 'website'],
    isOverdue: false,
  },
  {
    title: 'Email Campaign',
    description: 'Setup email marketing campaign',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['email', 'marketing'],
    isOverdue: false,
  },
  {
    title: 'Social Media',
    description: 'Manage social media presence',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['social-media', 'marketing'],
    isOverdue: false,
  },
  {
    title: 'SEO Optimization',
    description: 'Optimize website for search engines',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['seo', 'optimization'],
    isOverdue: false,
  },

  // Low Priority Tasks
  {
    title: 'Content Research',
    description: 'Research industry content trends',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['research', 'content'],
    isOverdue: false,
  },
  {
    title: 'Tool Evaluation',
    description: 'Evaluate new tools and services',
    priority: TaskPriority.LOW,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['tools', 'evaluation'],
    isOverdue: false,
  },
  {
    title: 'Archive Old Data',
    description: 'Archive old project data',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['archive', 'data'],
    isOverdue: false,
  },
  {
    title: 'Team Building',
    description: 'Plan team building activities',
    priority: TaskPriority.LOW,
    status: TaskStatus.PENDING,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user2@orgb.com',
    assignedTo: 'user2@orgb.com',
    tags: ['team-building', 'activities'],
    isOverdue: false,
  },
  {
    title: 'Process Documentation',
    description: 'Document team processes',
    priority: TaskPriority.LOW,
    status: TaskStatus.IN_PROGRESS,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['process', 'documentation'],
    isOverdue: false,
  },

  // Completed Tasks
  {
    title: 'Project Kickoff',
    description: 'Complete project kickoff meeting',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.COMPLETED,
    organizationId: ORGANIZATIONS.ORG_B.id,
    createdBy: 'user1@orgb.com',
    assignedTo: 'user1@orgb.com',
    tags: ['kickoff', 'meeting'],
    isOverdue: false,
    completedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
  },
];
